# 当代软件架构实践中的经验

> - 这门课的目标是创建一个可复用(在不同的工程中可以使用课中的数据结构库)的数据结构类库：DTLib.
> - 尽量使用**单重继承**的方式进行系统设计，可以实现多个接口的设计，继承的话只能是一对一的继承，千万不能让一个类继承多个父类
> - 尽量保持系统中只存在**单一的继承树** 
> - 尽量使用**组合关系**代替继承关系，创建一个顶层抽象父类来保证的
> - 吐槽C++：具有各种编程模式：支持面向过程/对象的编程、泛型编程，实践中多重继承只能让系统一堆Bug。
> - new操作失败会发生什么：失败的时候回抛出标准库的异常，这就给创建一个可复用的库带来了一定的困难
>
> ```c++
> noexcept 关键字：从C++11开始，我们能看到很多代码当中都有关键字noexcept。
> ```

> 该关键字告诉编译器，函数中不会发生异常,这有利于编译器对程序做更多的优化。
>  如果在运行时，noexecpt 函数向外抛出了异常（如果函数内部捕捉了异常并完成处理，这种情况不算抛出异常），程序会直接终止，调用std::terminate()函数，该函数内部会调用std::abort()终止程序。 

# 创建 DTLib::Object 类的意义

> - 遵循经典设计准则，所有数据都继承自 Object (单一继承树)
>
> - 定义动态内存申请的行为，提高代码的移植性(统一编译器行为)
>
> - # 顶层父类的接口定义
>
>   ​        
>
>   ```c++
>   class Object
>   {
>   public:
>       void *operator new (unsigned int size) noexcept;
>       void operator delete (void *p);
>       void *operator new[] (unsigned int size) noexcept;
>       void operator delete[] (void *p);
>       virtual ~Object() = 0;//子类都会有虚函数表的指针，动态类型识别
>   };
>   ```

 此处的new和delete是自定义的new和delete的操作符重载函数，定义它们的原因是：在不同的编译器下用new和delete的时候行为都是相同的。

# new和malloc的区别

## 1. 申请的内存所在位置

new操作符从自由存储区(free store)上为对象动态分配内存空间，malloc函数是从堆上动态分配内存空间。

```自由存储区是C++基于new操作符的一个抽象概念，凡是通过new操作符进行内存申请，该内存即为自由存储区。```

```而堆是操作系统中的术语，是操作系统所维护的一块特殊内存，用于程序的内存动态分配，C语言使用malloc从堆上分配内存，使用free释放已分配的对应内存。``` 

``` 那么自由存储区是否能够是堆（问题等价于new是否能在堆上动态分配内存），这取决于operator new 的实现细节。自由存储区不仅可以是堆，还可以是静态存储区，这都看operator new在哪里为对象分配内存。``` 

特别的，new甚至可以不为对象分配内存！定位new的功能可以办到这一点：

```c++
1 new (place_address) type
```

　　place_address为一个指针，代表一块内存的地址。当使用上面这种仅以一个地址调用new操作符时，new操作符调用特殊的operator new，也就是下面这个版本：

```
1 void * operator new (size_t,void *) //不允许重定义这个版本的operator new
```

　　这个operator new不分配任何的内存，它只是简单地返回指针实参，然后右new表达式负责在place_address指定的地址进行对象的初始化工作。

## 2.返回类型安全性

　　new操作符内存分配成功时，返回的是对象类型的指针，类型严格与对象匹配，无须进行类型转换，故new是符合类型安全性的操作符。而malloc内存分配成功则是返回void * ，需要通过强制类型转换将void*指针转换成我们需要的类型。

　　类型安全很大程度上可以等价于内存安全，类型安全的代码不会试图分配自己没被授权的内存区域。关于C++的类型安全性可说的又有很多了。

## 3.内存分配失败时的返回值

new内存分配失败时，会抛出bac_alloc异常，它不会返回NULL；malloc分配内存失败时返回NULL。

在使用C语言时，我们习惯在malloc分配内存后判断分配是否成功：

```c++
int *a  = (int *)malloc ( sizeof (int ));
if(NULL == a){...}
else {...}
```

从C语言走入C++阵营的新手可能会把这个习惯带入C++：

　从C语言走入C++阵营的新手可能会把这个习惯带入C++：

[![复制代码](https://common.cnblogs.com/images/copycode.gif)](javascript:void(0);)

```C++
1 int * a = new int();
2 if(NULL == a)
3 {
4     ...
5 }
6 else
7 {   
8     ...
9 }
```

　　实际上这样做一点意义也没有，因为new根本不会返回NULL，而且程序能够执行到if语句已经说明内存分配成功了，如果失败早就抛异常了。正确的做法应该是使用异常机制：

```C++
1 try
2 {
3     int *a = new int();
4 }
5 catch (bad_alloc)
6 {
7     ...
8 }
```

[![复制代码](https://common.cnblogs.com/images/copycode.gif)](javascript:void(0);)ttps://www.cnblogs.com/shilinnpu/p/8945637.html

## 4.是否需要指定内存大小

　　使用new操作符申请内存分配时无须指定内存块的大小，编译器会根据类型信息自行计算，而malloc则需要显式地指出所需内存的尺寸。

```c++
1 class A{...}
2 A * ptr = new A;
3 A * ptr = (A *)malloc(sizeof(A)); //需要显式指定所需内存大小sizeof(A);
```

## 5.是否调用构造函数/析构函数

使用new操作符来分配对象内存时会经历三个步骤：

　　第一步：调用operator new 函数（对于数组是operator new[]）分配一块足够大的，原始的，未命名的内存空间以便存储特定类型的对象。

　　第二步：编译器运行相应的构造函数以构造对象，并为其传入初值。

　　第三部：对象构造完成后，返回一个指向该对象的指针。

　　使用delete操作符来释放对象内存时会经历两个步骤：

　　第一步：调用对象的析构函数。

　　第二步：编译器调用operator delete(或operator delete[])函数释放内存空间。

 总之来说，new/delete会调用对象的构造函数/析构函数以完成对象的构造/析构。而malloc则不会。 

- [x] class A
  {
  public:
      A() :a(1), b(1.11){}
  private:
      int a;
      double b;
  };
  int main()
  {
      A * ptr = (A*)malloc(sizeof(A));
      return 0;
  }
- [ ] ![](图片\打断点.PNG)

可以看出A的默认构造函数并没有被调用，因为数据成员a,b的值并没有得到初始化，这也是上面我为什么说使用malloc/free来处理C++的自定义类型不合适，其实不止自定义类型，标准库中凡是需要构造/析构的类型通通不合适。

　　而使用new来分配对象时： 查看程序生成的汇编代码可以发现，A的默认构造函数被调用了

```c++
1 int main()
2 {
3     A * ptr = new A;
4 }
```

## 6.对数组的处理

　　C++提供了new[]与delete[]来专门处理数组类型:

```c++
1     A * ptr = new A[10];//分配10个A对象
```

　　使用new[]分配的内存必须使用delete[]进行释放：

```c++
1     delete [] ptr;
```

　　new对数组的支持体现在它会分别调用构造函数初始化每一个数组元素，释放对象时为每个对象调用析构函数。注意delete[]要与new[]配套使用，不然会找出数组对象部分释放的现象，造成内存泄漏。

至于malloc，它并不知道你在这块内存上要放的数组是啥东西，反正它就给你一块原始的内存，再给你个内存的地址就完事。所以如果要动态分配一个数组的内存，还需要我们手动制定数组的大小：

```c++
1 int * ptr = (int *) malloc( sizeof(int)* 10 );//分配一个10个int元素的数组
```

## 7.new与malloc是否可以相互调用

　　operator new /operator delete的实现可以基于malloc，而malloc的实现不可以去调用new。下面是编写operator new /operator delete 的一种简单方式，其他版本也与之类似：

## 7.new与malloc是否可以相互调用

　　operator new /operator delete的实现可以基于malloc，而malloc的实现不可以去调用new。下面是编写operator new /operator delete 的一种简单方式，其他版本也与之类似：

[![复制代码](https://common.cnblogs.com/images/copycode.gif)](javascript:void(0);)

```c++
 1 void * operator new (sieze_t size)
 2 {
 3     if(void * mem = malloc(size)
 4         return mem;
 5     else
 6         throw bad_alloc();
 7 }
 8 void operator delete(void *mem) noexcept
 9 {
10     free(mem);
11 }
```

[![复制代码](https://common.cnblogs.com/images/copycode.gif)](javascript:void(0);)

## 8.是否可以被重载

opeartor new /operator delete可以被重载。标准库是定义了operator new函数和operator delete函数的8个重载版本：

[![复制代码](https://common.cnblogs.com/images/copycode.gif)](javascript:void(0);)

```c++
 1 //这些版本可能抛出异常
 2 void * operator new(size_t);
 3 void * operator new[](size_t);
 4 void * operator delete (void * )noexcept;
 5 void * operator delete[](void *0）noexcept;
 6 //这些版本承诺不抛出异常
 7 void * operator new(size_t ,nothrow_t&) noexcept;
 8 void * operator new[](size_t, nothrow_t& );
 9 void * operator delete (void *,nothrow_t& )noexcept;
10 void * operator delete[](void *0,nothrow_t& ）noexcept;
```

[![复制代码](https://common.cnblogs.com/images/copycode.gif)](javascript:void(0);)

　　我们可以自定义上面函数版本中的任意一个，前提是自定义版本必须位于全局作用域或者类作用域中。太细节的东西不在这里讲述，总之，我们知道我们有足够的自由去重载operator new /operator delete ,以决定我们的new与delete如何为对象分配内存，如何回收对象。

　　而malloc/free并不允许重载。

## 9. 能够直观地重新分配内存

　　使用malloc分配的内存后，如果在使用过程中发现内存不足，可以使用realloc函数进行内存重新分配实现内存的扩充。realloc先判断当前的指针所指内存是否有足够的连续空间，如果有，原地扩大可分配的内存地址，并且返回原来的地址指针；如果空间不够，先按照新指定的大小分配空间，将原有数据从头到尾拷贝到新分配的内存区域，而后释放原来的内存区域。

　　new没有这样直观的配套设施来扩充内存。

## 10. 客户处理内存分配不足

在operator new抛出异常以反映一个未获得满足的需求之前，它会先调用一个用户指定的错误处理函数，这就是new-handler。new_handler是一个指针类型：

```C++
1 namespace std
2 {
3     typedef void (*new_handler)();
4 }
```

　　指向了一个没有参数没有返回值的函数,即为错误处理函数。为了指定错误处理函数，客户需要调用set_new_handler，这是一个声明于的一个标准库函数:

```C++
1 namespace std
2 {
3     new_handler set_new_handler(new_handler p ) throw();
4 }
```

　　set_new_handler的参数为new_handler指针，指向了operator new 无法分配足够内存时该调用的函数。其返回值也是个指针，指向set_new_handler被调用前正在执行（但马上就要发生替换）的那个new_handler函数。对于malloc，客户并不能够去编程决定内存不足以分配时要干什么事，只能看着malloc返回NULL。

 将上面所述的10点差别整理成表格： 

![](图片\new和malloc的总结.PNG)

# C++11异常处理 noexcept

### **1.简介**

在C语言中，如果程序的运行出现异常、错误，我们想提供方案处理这些异常时，我们面临许多问题，如： 
 （1）C语言没有提供统一（标准）的方式来处理错误； 
 （2）无法保证错误会被正确的处理； 
 （3）错误的传播无法控制，特别是在函数的嵌套调用时； 
 … …

当程序在运行时发生错误，使得程序的继续运行变得毫无意义时，C++中的异常机制给我们提供了一个解决方法。

### **2.C++03 异常处理（throw）**

C++98中，在函数声明时，我们使用throw指定一个函数可以抛出异常的类型。例如：

```C++
class Ex {
public:
  double getVal();
  void display() throw();
  void setVal(int i) throw (char*, double);
 private:
   int m_val;
};
```

上述函数的声明指定了该函数可以抛出异常的类型： 
 getVal() 可以抛出任何异常(默认)； 
 display() 不可以抛出任何异常； 
 setVal() 只可以抛出char* 和 double类型异常。

从功能上来说，C++98中的异常处理机制完全能满足我们的需要，正确的处理异常。 
 然而，编译器为了遵守C++语言标准，在编译时，只检查部分函数的异常规格（exception specification）。 
 注： 
 exception specification: 函数名字后面的throw表达式，或者noexcept。

```C++
// declaration
extern void funAny(void);                   //May throw ANY exception.
void check(void) throw (std::out_of_range); // May throw only std::out_of_range.

// implementation
void check(void) throw(std::out_of_range) {
    funAny();   // Compiler does not check if
    ...         // funAny(), or one of its 
}               // subordinates, only throws std::out_of_range!123456789
```

程序在运行时，如果funAny()抛出一个异常， 
 但是它的类型不是std::out_of_range， 异常处理机制将调用std::unexpected()（该函数自己也可能抛出异常）， 
 这个函数默认情况下会调用std::teminate().

### **3.C++11异常处理（noexcept）**

编译器在编译时能过做的检测非常有限，因此在C++11中异常声明被简化为以下两种情况： 
 （1）函数可以抛出任何异常(和之前的默认情况相同)； 
 （2）函数不可以抛出任何异常。

在C++11中，声明一个函数不可以抛出任何异常使用关键字noexcept.

```C++
void mightThrow(); // could throw any exceptions.
void doesNotThrow() noexcept; // does not throw any exceptions.
```

下面两个函数声明的异常规格在语义上是相同的，都表示函数不抛出任何异常。

```
void old_stytle() throw();
void new_style() noexcept;12
```

它们的区别在于程序运行时的行为和编译器优化的结果。 
 使用throw()， 如果函数抛出异常，异常处理机制会进行栈回退，寻找(一个或多个）catch语句。 
 此时，检测catch可以捕捉的类型，如果没有匹配的类型，std::unexpected()会被调用。 
 但是std::unexpected()本身也可能抛出异常。 
 如果std::unexpected()抛出的异常对于当前的异常规格是有效的， 
 异常传递和栈回退会像以前那样继续进行。 
 这意味着，如果使用throw， 编译器几乎没有机会做优化。 
 事实上，编译器甚至会让代码变得更臃肿、庞大： 
 （1）栈必须被保存在回退表中； 
 （2）所有对象的析构函数必须被正确的调用（按照对象构建相反的顺序析构对象）； 

（3）编译器可能引入新的传播栅栏（propagation barriers）、引入新的异常表入口，使得异常处理的代码变得更庞大； 
 （4）内联函数的异常规格（exception specification）可能无效的。

当使用noexcept时，std::teminate()函数会被立即调用，而不是调用std::unexpected(); 
 因此，在异常处理的过程中，编译器不会回退栈，这为编译器的优化提供了更大的空间。

简而言之，如果你知道你的函数绝对不会抛出任何异常，应该使用noexcept, 而不是throw().

数据结构库里面的所有的类都继承自顶层object顶层父类的话，我们就可以保证从堆空间里面创建数据结构对象的时候必然使用我们提供的new和delete的实现了



### C++11 之 override

# 作用

在成员函数声明或定义中，override 确保该函数为虚函数并覆写来自基类的虚函数。

 位置：函数调用运算符之后，函数体或纯虚函数标识 “= 0” 之前。 



